CREATE TABLE `pessoas` (
`Id` int(10) UNSIGNED NULL DEFAULT NULL,
`Nome` VARCHAR(50) NULL DEFAULT NULL,
`sobreNome` VARCHAR(50) NULL DEFAULT NULL,
`Endereco` VARCHAR(50) NULL DEFAULT NULL,
`Genero` VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=InnoDB
;